alias btw 'echo i use nixos, btw'
alias ebash 'nvim ~/dotfiles/config/bash/.bashrc'
alias efish 'nvim ~/dotfiles/config/fish/config.fish'
alias ehome 'nvim ~/dotfiles/home.nix'
alias eshells 'nvim ~/dotfiles/shells/settings.nix'
alias esystem 'nvim ~/dotfiles/configuration.nix'
alias ezsh 'nvim ~/dotfiles/config/zsh/.zshrc'
alias nrs 'sudo nixos-rebuild switch --flake '\''path:/home/pablo/dotfiles#nixos-btw'\'''
alias rbash 'source ~/.bashrc'
alias rfish 'source ~/.config/fish/config.fish'
alias rzsh 'source ~/.config/zsh/.zshrc'
